apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwm-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/wwwm-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwm-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce           # 단일 노드에서만 Read/Write 가능한 모드
  storageClassName: manual    # 동적 프로비저닝 없이, 직접 PV를 만들겠다는 의미
  resources:
    requests:
      storage: 10Gi
  volumeName: wwwm-mysql-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
data:
  .my.cnf: |
    [client]
    user=root
    password=<PASSWORD>
    host=127.0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwm-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wwwm-mysql
  template:
    metadata:
      labels:
        app: wwwm-mysql
    spec:
      # master 노드의 NoSchedule taint를 허용
      # 미상의 원인으로 Worker Node를 위한 Openstack Instance가 중지되는 문제 일시적 조치
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: wwwm-mysql
          image: mysql:latest
          # Failover를 위한 readinessProbe 설정
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h127.0.0.1"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: <PASSWORD>
            - name: MYSQL_ROOT_HOST # 루트 계정을 원격 접속 허용하려면 MYSQL_ROOT_HOST=%를 추가
              value: "%"
            - name: MYSQL_DATABASE
              value: wwwm_db
            - name: MYSQL_USER
              value: wwwm_user
            - name: MYSQL_PASSWORD
              value: <PASSWORD>
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
            requests:
              memory: "800Mi"
              cpu: "500m"
          volumeMounts:
            - name: wwwm-mysql-data
              mountPath: /var/lib/mysql
        # mysqld_exporter sidecar
        - name: wwwm-mysql-exporter
          image: prom/mysqld-exporter:latest
          args:
            - "--config.my-cnf=/config/.my.cnf"
          ports:
            - containerPort: 9104
          resources:
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: mysql-exporter-config
              mountPath: /config/.my.cnf
              subPath: .my.cnf
      volumes:
        - name: wwwm-mysql-data
          persistentVolumeClaim:
            claimName: wwwm-mysql-pvc
        - name: mysql-exporter-config
          configMap:
            name: mysql-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: wwwm-mysql-service
spec:
  type: NodePort
  selector:
    app: wwwm-mysql
  ports:
    # MySQL
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32306
    # mysqld_exporter
    - name: metrics
      protocol: TCP
      port: 9104
      targetPort: 9104
      nodePort: 32104