apiVersion: v1
kind: ConfigMap
metadata:
  name: wwwm-spring-be-v2-config
data:
  application-private.yml: |-
    spring:
      application:
        name: WHEN-WILL-WE-MEET
      datasource:
        # 외부 IP 주소 대신 wwwm-mysql-service 사용
        url: jdbc:mysql://wwwm-mysql-service:3306/wwwm_db?allowPublicKeyRetrieval=true
        username: root
        password: <PW>
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        show-sql: true
      jackson:
        time-zone: UTC

    constant:
      appointment-expiration-time: 30
      time-slot-unit-time: 10

    jwt:
      secret:
        key: <SECRET>
      public-url: /api/v2/users/auth/signup, /api/v2/users/auth/login, /
      utils:
        authorization-header: Authorization
        id-key: id
        bearer-prefix: Bearer
        token-time: 3600000