apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwm-spring-be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wwwm-spring-be
  template:
    metadata:
      labels:
        app: wwwm-spring-be
    spec:
      containers:
      - name: wwwm-spring-be
        image: judemin/wwwm-spring-be:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "800m"
            memory: "400Mi"
          limits:
            cpu: "1"
            memory: "800Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10